#!/bin/bash
# Continuous Integration build script.

# Set up rvm
export PATH=$PATH:~/.rvm/bin
set +x # Silence tracing
source ~/.rvm/scripts/rvm
set -e # Exit on any error
cd .   # Kick off the rvmrc
set -x # Resume tracing

# Verify environment.
ruby -v
gem env gemdir

# Install gems.
bundle --no-color install

# Set display for selenium
export DISPLAY=:42.0

# Prepare and run the tets.
export SPEC_OPTS="-f s"
rake db:create:all db:migrate spec

# Determine what revision we're testing.
revision=`git show --format=oneline | head -1 | cut -d ' ' -f 1`

# Deploy to staging.
cap staging deploy -s branch=$revision

# Ensure that some key pages display properly.
curl http://lifeviz.staging.westarete.com/ | grep -3 "Animalia"

